import type { IEnemy } from '../types/Enemy';

export const ENEMIES: IEnemy[] = [
  {
    id: 1,
    name: 'Странник тьмы',
    color: '#f6c453',
    symbol: '◆',
    hp: 62,
    speed: 0.88,
    rewardEnergy: 12,
    currencyDrop: 1,
    dropChance: 0.15,
    description: 'Обычный противник без сильной специализации.',
  },
  {
    id: 2,
    name: 'Быстрый вестник',
    color: '#7dd3fc',
    symbol: '➤',
    hp: 42,
    speed: 1.35,
    rewardEnergy: 13,
    currencyDrop: 1,
    dropChance: 0.12,
    description: 'Мало здоровья, но быстро проходит опасные участки дороги.',
  },
  {
    id: 3,
    name: 'Каменный носитель',
    color: '#c4b5fd',
    symbol: '⬢',
    hp: 155,
    speed: 0.58,
    rewardEnergy: 22,
    currencyDrop: 2,
    dropChance: 0.18,
    description: 'Медленный тяжёлый враг с большим запасом здоровья.',
  },
  {
    id: 4,
    name: 'Страж разлома',
    color: '#fb7185',
    symbol: '✦',
    hp: 310,
    speed: 0.7,
    rewardEnergy: 32,
    currencyDrop: 3,
    dropChance: 0.25,
    description: 'Элитный противник. При прорыве наносит базе двойной урон.',
  },
  {
    id: 5,
    name: 'Предвестник бездны',
    color: '#f59e0b',
    symbol: '◈',
    hp: 760,
    speed: 0.42,
    rewardEnergy: 95,
    currencyDrop: 5,
    dropChance: 0.5,
    description: 'Очень медленный мини-босс с высокой наградой.',
  },
  {
    id: 6,
    name: 'Владыка разлома',
    color: '#ef4444',
    symbol: '⬟',
    hp: 1850,
    speed: 0.3,
    rewardEnergy: 240,
    currencyDrop: 10,
    dropChance: 1,
    description: 'Главный босс десятой волны: огромный запас здоровья и тяжёлый удар по базе.',
  },
  {
    id: 7,
    name: 'Кубик судьбы',
    color: '#ffffff',
    symbol: '⚀',
    hp: 70,
    speed: 0.84,
    rewardEnergy: 0,
    currencyDrop: 0,
    dropChance: 1,
    description: 'Скрытый бонусный враг. Грань определяет здоровье, скорость и награду очками слияния.',
  },
];
