export const NORMAL_MUSIC_TRACKS = [
  '/audio/music/normal/normal_wave_01_first_light.mp3',
  '/audio/music/normal/normal_wave_02_dusty_path.mp3',
  '/audio/music/normal/normal_wave_03_watchers_on_the_wall.mp3',
  '/audio/music/normal/normal_wave_04_steady_advance.mp3',
  '/audio/music/normal/normal_wave_05_sands_of_the_covenant.mp3',
  '/audio/music/normal/normal_wave_06_hidden_footsteps.mp3',
  '/audio/music/normal/normal_wave_07_guardians_march.mp3',
  '/audio/music/normal/normal_wave_08_shadows_on_the_road.mp3',
  '/audio/music/normal/normal_wave_09_faith_under_fire.mp3',
  '/audio/music/normal/normal_wave_10_road_of_trials.mp3',
  '/audio/music/normal/normal_wave_11_banners_in_the_wind.mp3',
  '/audio/music/normal/normal_wave_12_before_the_storm.mp3',
  '/audio/music/normal/normal_wave_13_unbroken_line.mp3',
  '/audio/music/normal/normal_wave_14_last_watch.mp3',
  '/audio/music/normal/normal_wave_15_path_of_resolve.mp3',
] as const;

export const BOSS_MUSIC_TRACKS = [
  '/audio/music/boss/boss_wave_01_herald_of_the_abyss.mp3',
  '/audio/music/boss/boss_wave_02_throne_of_the_rift.mp3',
  '/audio/music/boss/boss_wave_03_judgment_approaches.mp3',
  '/audio/music/boss/boss_wave_04_colossus_at_the_gate.mp3',
  '/audio/music/boss/boss_wave_05_final_covenant.mp3',
] as const;

export const SFX = {
  uiClick: '/audio/sfx/ui/ui_button_click.mp3',
  uiConfirm: '/audio/sfx/ui/ui_button_confirm.mp3',
  uiCancel: '/audio/sfx/ui/ui_button_cancel.mp3',
  uiPanelOpen: '/audio/sfx/ui/ui_panel_open.mp3',
  uiPanelClose: '/audio/sfx/ui/ui_panel_close.mp3',
  uiBlocked: '/audio/sfx/ui/ui_action_blocked.mp3',
  purchaseSuccess: '/audio/sfx/ui/ui_purchase_success.mp3',
  purchaseFailed: '/audio/sfx/ui/ui_purchase_failed.mp3',

  waveStart: '/audio/sfx/waves/wave_start.mp3',
  waveComplete: '/audio/sfx/waves/wave_complete.mp3',
  bossWarning: '/audio/sfx/waves/boss_wave_warning.mp3',
  miniBossSpawn: '/audio/sfx/waves/miniboss_spawn.mp3',
  bossSpawn: '/audio/sfx/waves/boss_spawn.mp3',
  miniBossDefeated: '/audio/sfx/waves/miniboss_defeated.mp3',
  bossDefeated: '/audio/sfx/waves/boss_defeated.mp3',
  victory: '/audio/sfx/waves/victory_fanfare.mp3',
  defeat: '/audio/sfx/waves/defeat_stinger.mp3',

  redShot: [
    '/audio/sfx/towers/red/tower_red_shot_01.mp3',
    '/audio/sfx/towers/red/tower_red_shot_02.mp3',
    '/audio/sfx/towers/red/tower_red_shot_03.mp3',
  ],
  redCritical: '/audio/sfx/towers/red/tower_red_critical.mp3',
  redExecute: '/audio/sfx/towers/red/tower_red_execute.mp3',
  redHorizon: '/audio/sfx/towers/red/tower_red_horizon_shot.mp3',

  blueLaser: [
    '/audio/sfx/towers/blue/tower_blue_laser_01.mp3',
    '/audio/sfx/towers/blue/tower_blue_laser_02.mp3',
    '/audio/sfx/towers/blue/tower_blue_laser_03.mp3',
  ],
  blueRicochet: '/audio/sfx/towers/blue/tower_blue_ricochet.mp3',
  blueChain: '/audio/sfx/towers/blue/tower_blue_chain.mp3',
  blueNetwork: '/audio/sfx/towers/blue/tower_blue_network.mp3',

  greenPulse: [
    '/audio/sfx/towers/green/tower_green_pulse_01.mp3',
    '/audio/sfx/towers/green/tower_green_pulse_02.mp3',
    '/audio/sfx/towers/green/tower_green_pulse_03.mp3',
  ],
  greenDouble: '/audio/sfx/towers/green/tower_green_double_attack.mp3',
  greenBurst: '/audio/sfx/towers/green/tower_green_burst.mp3',
  greenOverload: '/audio/sfx/towers/green/tower_green_overload.mp3',

  enemyDeath: [
    '/audio/sfx/enemies/enemy_death_01.mp3',
    '/audio/sfx/enemies/enemy_death_02.mp3',
    '/audio/sfx/enemies/enemy_death_03.mp3',
  ],
  enemyEscape: '/audio/sfx/enemies/enemy_escape.mp3',
  enemyEliteSpawn: '/audio/sfx/enemies/enemy_elite_spawn.mp3',
  cubeSpawn: '/audio/sfx/enemies/cube_spawn.mp3',
  cubeDestroy: '/audio/sfx/enemies/cube_destroy.mp3',
  cubeReward: [
    '/audio/sfx/enemies/cube_reward_01.mp3',
    '/audio/sfx/enemies/cube_reward_02.mp3',
    '/audio/sfx/enemies/cube_reward_03.mp3',
    '/audio/sfx/enemies/cube_reward_04.mp3',
    '/audio/sfx/enemies/cube_reward_05.mp3',
    '/audio/sfx/enemies/cube_reward_06.mp3',
  ],

  fusionStart: '/audio/sfx/fusion/fusion_random_start.mp3',
  fusionCommon: '/audio/sfx/fusion/fusion_random_common.mp3',
  fusionUncommon: '/audio/sfx/fusion/fusion_random_uncommon.mp3',
  fusionRare: '/audio/sfx/fusion/fusion_random_rare.mp3',
  fusionEpic: '/audio/sfx/fusion/fusion_random_epic.mp3',
  fusionLegendary: '/audio/sfx/fusion/fusion_random_legendary.mp3',
  superReady: '/audio/sfx/fusion/super_fusion_ready.mp3',
  superTarget: '/audio/sfx/fusion/super_fusion_target_select.mp3',
  superComplete: '/audio/sfx/fusion/super_fusion_complete.mp3',
  superLevelUp: '/audio/sfx/fusion/super_fusion_level_up.mp3',

  baseHitLight: '/audio/sfx/base/base_hit_light.mp3',
  baseHitHeavy: '/audio/sfx/base/base_hit_heavy.mp3',
  baseCritical: '/audio/sfx/base/base_health_critical.mp3',
} as const;

export const PRIORITY_SFX = [
  SFX.uiClick,
  SFX.waveStart,
  SFX.waveComplete,
  SFX.bossWarning,
  SFX.bossSpawn,
  SFX.bossDefeated,
  SFX.baseHitLight,
  SFX.baseHitHeavy,
  SFX.cubeSpawn,
  SFX.cubeDestroy,
  SFX.fusionCommon,
  SFX.superComplete,
  SFX.redShot[0],
  SFX.blueLaser[0],
  SFX.greenPulse[0],
  SFX.enemyDeath[0],
] as const;
